import os

INTERFACE_FILE_NAME_MAP = {}
STRUCT_FILE_NAME_MAP = {}
CWD = os.getcwd()
SERVICE_NAME = CWD.split('/')[-1]
RUN_COVERAGE_FILE = ""
MOCK_BEGIN_TRANSACTION = None
MOCK_GET_EXISTING_TRANSACTOR_FROM_CONTEXT = None
MOCK_ADD_TRANSACTOR_TO_CONTEXT = None